services:
  php:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: toca_dos_instrumentos

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db:db
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: 123
